language: cpp
sudo: required
dist: trusty
compiler:
- g++
os:
- linux

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-5
            - g++-5
            - lcov


branches:
  only:
  - master

before_install:
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 50

install:
    - cd ${TRAVIS_BUILD_DIR}
    - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.13.orig.tar.gz
    - tar xf lcov_1.13.orig.tar.gz
    - cd lcov-1.13/
    - sudo make install
    - cd ..
    - gem install coveralls-lcov
    - lcov --version
    - g++ --version

script: ./run_all_test.sh

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info 'test/googletest/*' '/usr/*' --output-file coverage.info # filter out system
  - coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info

notifications:
  email:
    - rocki5555@gmail.com

env:
  global:
  - LANG="en_US.UTF-8"
